# Generated by Django 5.0 on 2024-01-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='User Name')),
                ('device_id', models.TextField(blank=True, verbose_name='Device ID')),
                ('permission', models.BooleanField(default=False)),
            ],
        ),
    ]
