# Generated by Django 4.2 on 2024-02-25 13:17

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Name")),
                (
                    "photo",
                    models.ImageField(
                        upload_to=main.models.upload_media_path, verbose_name="Photo"
                    ),
                ),
            ],
        ),
    ]
