# Generated by Django 5.0 on 2024-01-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_profile_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='device_id',
            field=models.TextField(blank=True, unique=True, verbose_name='Device ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(verbose_name='User Name'),
        ),
    ]
