# Generated by Django 5.0 on 2024-01-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_profile_options_profile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='device_id',
            field=models.TextField(blank=True, max_length=256, unique=True, verbose_name='Device ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(max_length=150, verbose_name='User Name'),
        ),
    ]
