# Generated by Django 5.0 on 2024-01-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_profile_device_id_alter_profile_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['permission'], name='main_profil_permiss_aa17cf_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['created_at'], name='main_profil_created_374fd2_idx'),
        ),
    ]
